; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; C:\Users\44998\Documents\PlatformIO\Projects
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-n16r8]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
upload_port = COM16
monitor_speed = 115200
board_build.arduino.memory_type = dio_qspi
board_build.flash_mode = dio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY=y
    -DCONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP=0
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
board_build.filesystem = spiffs
